name: test-py2

on: [push]

jobs:
  testpy2:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    # Use the python version installed by Ubuntu 18.04 (version 2.7.15),
    # so we can use precompiled gdal and protobuf
    - name: Install xmllint and GDAL
      run: sudo apt-get install -y libxml2-utils gdal-bin libgdal-dev python-gdal
    - name: "Install python dependencies: cram and lxml"
      run: |
        python -m pip install --upgrade pip
        pip install cram lxml
    - name: Testing the code with cram
      run: |
        cram testfiles/basic_py2.t

