name: test-py3

on: [push]

jobs:
  testpy3:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    # Use the python version installed by Ubuntu 20.04 (version 3.8.5),
    # so we can use precompiled gdal and protobuf
    - name: Install xmllint and GDAL
      run: sudo apt-get install -y libxml2-utils gdal-bin libgdal-dev python3-gdal
    - name: "Install python dependencies: cram and lxml"
      run: |
        python -m pip install --upgrade pip
        pip install cram lxml
    - name: Testing the code with cram
      run: |
        cram testfiles/basic.t

